---
title: "Using uniprotProteinView"
author:
- name: "George Zorn
email: george.zorn@mail.utoronto.ca
package: uniprotProteinView
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview
This package was made to allow for users to draw one or more 2D schematics of proteins from the data provided by UniProt.

Workflow:
1. Get UniProt XML data
2. Parse XML data into lists of features and convert to dataFrame
3. Generate blank plots
4. Fill out plots with features

# Get UniProt XML Data
This package get xml data from UniProt by either one of three options:

1. Reading from local file using `getProteinLocal()`
2. Reading from the UniProt webpage using `getProteinRemote()`
3. Downloading the UniProt protein xml file and reading from that using `getProteinRemoteD()`

```{eval=TRUE, echo=TRUE}
    method1Xmls <- uniprotProteinView::getProteinLocal("Q9D270.xml")
    method2Xmls <- uniprotProteinView::getProteinRemote("Q9D270")
    method3Xmls <- uniprotProteinView::getProteinRemoteD("Q9D270")
```

Method 1 will require the file name in full, while method 2 and 3 only need the protein ID. All three of these methods can take in a vector to allow the user to process and view multiple proteins at the same time

# Parse XML data into lists of features and convert to dataFrame
To parse data into plots, the user first needs to get a list of features for their protein(s). Here it is important to distinguish that this package data by having a parent list. This parent list then contains sub lists for each protein. Thus for the feature list, it will be a parent list, with lists of features for each protein that was originally loaded.

```{eval=TRUE, echo=TRUE}
    xmls <- getProteinRemote(c("Q04206", "Q9D270"))
    features <- getFeatureList(xmls)
```

This code will give a list of feature lists for each protein, in this examples case, for the proteins Q04206 and Q9D270. The next step is to get a dataFrame

```{eval=TRUE, echo=TRUE}
    xmls <- getProteinRemote(c("Q04206", "Q9D270"))
    features <- getFeatureList(xmls)
    data <- featuresToDataFrame(features)
```

Here the previously obtained features list is used to return a list of two dataFrames, one for each protein.

# Generate blank plots
After all data is parsed, the next step is to generate the base plots using the function `drawPlot()`

```{eval=TRUE, echo=TRUE}
    xmls <- getProteinRemote(c("Q04206", "Q9D270"))
    features <- getFeatureList(xmls)
    data <- featuresToDataFrame(features)
    plots <- drawPlot(data)
```

Here, plots is a list of plots for each protein. These plots contain no content yet.


# Fill out plots with features
Next is to fill out the plots with various data, from here there are two primary functions `elementIfMatch()` and `elementIfContains()`. The formal will search through the provided dataFrame and use any entry that matches the pattern, while the later function will search if any of the entries in the dataFrame contains somewhere within it the pattern string.

```{eval=TRUE, echo=TRUE}
    xmls <- getProteinRemote(c("Q04206", "Q9D270"))
    features <- getFeatureList(xmls)
    data <- featuresToDataFrame(features)
    plots <- drawPlot(data)
    plots <- elementIfMatch(plots, data, "chain")
    plots <- elementIfContains(plots, data, "phos")
    plotProteins(plots)
```

The above code will plot both proteins showing the main chain and all phosphate modifications. It also introduces the function `plotProteins()`, this function works allow all plots within the list to be displays at the same time, and is the recommended way to plot proteins. The function is a wrapper over the function `cowplot::plot_grid(plotlist=plots)`.

The package also provides some untility functions to help draw some common elements found: `drawChain()`, `drawMotifs()`, `drawRegions()`, `drawDomains()`, `drawBetaStrands()`, `drawHelicies()`, and `drawTurns()`.